<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2022/8/25
 * Time: 14:30
 */
namespace app\index\controller;

use think\Controller;
use think\Db;
use app\index\model\UserModal;
use think\Model;

class User extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function scope(){
        //$User = new UserModal();
        $r = UserModal::scope('name','aa')->age(10)->select();
        print_r(Db::getLastSql($r));
        dump($r);
    }
}